SELECTED_TEAMS = {
    "Sean": [
        "Ohio State",
        "Miami",
        "LSU",
        "Navy",
        "Army",
        "Jacksonville State",
    ],
    "Randy": [
        "Notre Dame",
        "Kansas State",
        "Louisiana",
        "Utah",
        "East Carolina",
        "Western Kentucky",
    ],
    "Justin": [
        "Oregon",
        "Clemson",
        "Indiana",
        "Georgia Tech",
        "Tennessee",
        "Nebraska",
    ],
    "Matthew": [
        "Penn State",
        "Memphis",
        "SMU", 
        "Illinois",
        "Oklahoma",
        "Miami (OH)",
    ],
    "Futa": [
        "Georgia",
        "Arizona State",
        "South Carolina",
        "Buffalo",
        "Arkansas State",
        "Colorado State",
    ],
    "Ben": [
        "Texas",
        "UNLV",
        "Michigan",
        "Ole Miss",
        "Kansas",
        "UTSA",
    ],
    "Austin": [
        "Toledo",
        "Alabama",
        "San José State",
        "Iowa State",
        "Florida",
        "Baylor",
    ],
    "Nick": [
        "Liberty",
        "James Madison",
        "BYU",
        "Georgia Southern",
        "Missouri",
        "USC",  
    ],
    "Oliver": [
        "Boise State",
        "Tulane",
        "Texas Tech",
        "Louisville",
        "Texas A&M",
        "Ohio",
    ],
}

ALL_SELECTED_TEAMS = sorted({team for teams in SELECTED_TEAMS.values() for team in teams})